### PR TITLE
Create pl_pl.lang

### PR DESCRIPTION
**Pull request by DoloresMcDoodle**
Polish translation for this mod

### CODE REVIEW

**Review by HyCraftHD — CHANGES_REQUESTED** [review]
Hello, thank you for you translation first!

In 1.14 we need a json file as a translation and not a key value mapping like in 1.12. Please rebase or make a new pull for 1.12 and change this file to a json file

**Comment by HyCraftHD** [comment]
Actually I mean the file and not the title :D Also if so its the wrong branch

**Comment by DoloresMcDoodle** [comment]
I repair it. I'm sorry for the trouble.

**Review by HyCraftHD — APPROVED** [review]
This seems good, Thanks

**Comment by HyCraftHD** [comment]
We will be updating the version on curseforge soon. Thanks

**Pull request merged**
