### PR TITLE
Dutch Localization

### PR DESCRIPTION
**Pull request by HeresHavi**

### CODE REVIEW

**Comment by HyCraftHD** [comment]
Thank you very much for the translation.

**Review by HyCraftHD — CHANGES_REQUESTED** [review]
I only need the file in /src/main/resources and not in /src/generated
When you change that I can merge the pull request

**Comment by HeresHavi** [comment]
> I only need the file in /src/main/resources and not in /src/generated
> When you change that I can merge the pull request

The file has been removed from /src/generated

**Comment by HyCraftHD** [comment]
Thank you very much

**Pull request merged**
